version: "3.9"

services:
  db:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: pollution-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: pollution-rabbitmq
    restart: always
    ports:
      - "5672:5672"      # for backend
      - "15672:15672"    # management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}

  app:
      build: .
      container_name: pollution-backend
      restart: always
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
      depends_on:
        - db
        - rabbitmq
      environment:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_HOST: db
        DB_PORT: ${DB_PORT}

        SERVER_HOST: ${SERVER_HOST}
        SERVER_PORT: ${SERVER_PORT}

        AMQP_USER: ${AMQP_USER}
        AMQP_PASSWORD: ${AMQP_PASSWORD}
        AMQP_HOST: rabbitmq
        AMQP_PORT: ${AMQP_PORT}


volumes:
  postgres_data:

