version: "3.9"

services:
  db:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: pollution-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: pollution-rabbitmq
    restart: always
    ports:
      - "5672:5672"      # for backend
      - "15672:15672"    # management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${AMQP_USER}
      RABBITMQ_DEFAULT_PASS: ${AMQP_PASSWORD}

volumes:
  postgres_data:

