definitions:
  pollution.Pollution:
    properties:
      is_anomaly:
        type: boolean
      latitude:
        type: number
      longitude:
        type: number
      pollutant:
        type: string
      time:
        type: string
      value:
        type: number
    type: object
  pollution.PollutionDensity:
    properties:
      density:
        type: number
      pollutant:
        type: string
      time:
        type: string
    type: object
  pollution.PollutionValueResponse:
    properties:
      pollutant:
        type: string
      time:
        type: string
      value:
        type: number
    type: object
info:
  contact: {}
  description: API documentation for pollution-tracker app
  title: pollution-tracker API
paths:
  /api/anomalies:
    get:
      description: Gets anomalies for a given time range
      parameters:
      - description: Start time
        in: query
        name: from
        required: true
        type: string
      - description: End time
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Anomalies
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/pollution.Pollution'
              type: array
            type: object
        "400":
          description: Invalid params
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to fetch pollution entries from database
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gets anomalies for range
      tags:
      - anomalies
  /api/pollutants:
    get:
      description: Gets distinct pollutants that exists in database
      produces:
      - application/json
      responses:
        "200":
          description: Pollutants
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to fetch pollutants entries from database
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gets pollutants
      tags:
      - pollutants
  /api/pollutions:
    get:
      description: Gets all pollution values for given time range.
      parameters:
      - description: Start time
        in: query
        name: from
        required: true
        type: string
      - description: End time
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Pollution values
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/pollution.Pollution'
              type: array
            type: object
        "400":
          description: Invalid params
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to fetch pollution entries from database
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gets pollution values
      tags:
      - pollutions
    post:
      consumes:
      - application/json
      description: Posts a new pollution entry
      parameters:
      - description: Request of adding a new pollution entry
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pollution.Pollution'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully received the pollution entry
          schema:
            type: string
        "400":
          description: Failed to marshal request body
          schema:
            type: string
        "500":
          description: Failed to publish pollution entry to RabbitMQ queue
          schema:
            type: string
      summary: Posts pollution entry
      tags:
      - pollutions
  /api/pollutions/{latitude}/{longitude}:
    get:
      description: Gets pollution values for given location and time range
      parameters:
      - description: latitude
        in: path
        name: latitude
        required: true
        type: string
      - description: longitude
        in: path
        name: longitude
        required: true
        type: string
      - description: Start time
        in: query
        name: from
        type: string
      - description: End time
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Pollution Values
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/pollution.PollutionValueResponse'
              type: array
            type: object
        "400":
          description: Invalid params
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to fetch pollution entries from database
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gets pollution values
      tags:
      - pollutions
  /api/pollutions/density/rect:
    get:
      description: Gets pollution densities for a given rect and time range
      parameters:
      - description: latFrom
        in: query
        name: latFrom
        required: true
        type: number
      - description: latTo
        in: query
        name: latTo
        required: true
        type: number
      - description: longFrom
        in: query
        name: longFrom
        required: true
        type: number
      - description: longTo
        in: query
        name: longTo
        required: true
        type: number
      - description: from
        in: query
        name: from
        required: true
        type: string
      - description: to
        in: query
        name: to
        required: true
        type: string
      - description: pollutant
        in: query
        name: pollutant
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Pollution Densities
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/pollution.PollutionDensity'
              type: array
            type: object
        "400":
          description: Invalid params
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Failed to fetch pollution entries from database
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Gets pollution densities of rect
      tags:
      - pollutions
swagger: "2.0"
